#The URL of the webhook to send messages to
webhookUrl = "http://127.0.0.1:5140/awh"
#The token to authenticate with the webhook
token = ""
#Only send webhook when player leave(true/false)
send_only_on_leave = true
#Time consumption threshold (min)
threshold = 10.0
